Feature map
OleksiiVTS/goit-team-prog-g7 pull request #27
Opened 2023-02-12 18:50 UTC by SSSerg05

2023-02-12 19:21 UTC, Solembum05 requested changes

2023-02-12 19:21 UTC, Solembum05 commented on src/css/styles.css
> +  .map-contacts-card {
На ширині 1024px  поле має відставати на 47 px. Я б додав лівий маржин 32пх

2023-02-12 19:21 UTC, Solembum05 commented on src/index.html
> +                      value="095 555 95 33">
Мені здається що номери телефонів треба реалізувати як список з елементів і телефони з посиланням, щоб при натисканні юзер міг позвонити. Інпути ми використовуємо для отримання фідбеку, бронювати столик, номер і тд. А в тебе це просто виглядає як інпут

2023-02-12 19:28 UTC, SSSerg05 commented on src/index.html
> +              <h3 class="map-sub-title">MIMIHO</h3>
ця назва не написана а взята з макету

2023-02-12 19:30 UTC, Solembum05 commented on src/index.html
> +              <h3 class="map-sub-title">MIMIHO</h3>
Сорі, мій косяк, воно дуже дивно на макеті виглядає

2023-02-12 19:31 UTC, SSSerg05 commented on src/index.html
> +              <h3 class="map-sub-title">MIMIHO</h3>
тому що шрифт не той

2023-02-12 19:35 UTC, SSSerg05 commented on src/css/styles.css
> +  .map-contacts-card {
до карти також? але з правий?

2023-02-12 19:40 UTC, Solembum05 commented on src/css/styles.css
> +  .map-contacts-card {
Так, до речі, а там не має бути контейнер який би центрував контент?

2023-02-12 19:41 UTC, SSSerg05 commented on src/css/styles.css
> +  .map-contacts-card {
278 він там і є

2023-02-12 19:44 UTC, Solembum05 commented on src/css/styles.css
> +  .map-contacts-card {
На таблеті є тільки ширина і стандартні падінги по 15пх, цим же контейнером можна і стиснуни на 32пх

2023-02-13 07:41 UTC, SSSerg05 commented on src/index.html
> +                      value="095 555 95 33">
done

2023-02-13 07:42 UTC, SSSerg05 commented on src/css/styles.css
> +  .map-contacts-card {
done + на 1280 також

2023-02-13 10:17 UTC, Solembum05 requested changes

2023-02-13 10:27 UTC, SSSerg05 commented on src/css/styles.css
> +  margin-bottom: 16px;
done

2023-02-13 10:28 UTC, SSSerg05 commented on src/css/styles.css
> +  margin-bottom: 16px;
відео тільки дома подивитися зможу

2023-02-13 10:28 UTC, Solembum05 commented on src/css/styles.css
> +  margin-bottom: 16px;
Відео то для наглядності

2023-02-13 10:57 UTC, SSSerg05 commented on src/css/styles.css
> +.map-field-address {
done

2023-02-13 11:02 UTC, Solembum05 commented on src/css/styles.css
> +.map-field-address {
+++

2023-02-13 11:03 UTC, Solembum05 approved these changes

2023-02-13 11:52 UTC, OleksiiVTS requested changes
Необхідно змінити падінги у секціях перелому.

2023-02-13 11:55 UTC, OleksiiVTS approved these changes

2023-02-16 15:40 UTC, closed without merging